Download extension REST Client
###
POST http://localhost:8000/products
Content-Type: application/json

{
  "name": "casaco",
  "price": 70.0
}

###
GET http://localhost:8000/products/349ac6ee-b188-4065-a56b-4624384c4380
Content-Type: application/json

###
PUT http://localhost:8000/products/b0b20206-cea2-4694-b97c-d5d46b23f65b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDA0MDQ5NTQsInN1YiI6IjEwODdiYzg1LTI4MzUtNDZjOC1hNThlLWE4YzNhOTk0MWZhOCJ9.BahMFquSOnkWxh6WqUBZnr4ZBvL4ZKIXDk-dItB-ko4

{
  "name": "calça jeans",
  "price": 200.0
}

###
DELETE http://localhost:8000/products/f9f57720-ee77-4193-b347-6f0c48fc1eae
Content-Type: application/json

###
GET http://localhost:8000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDAzNDY5NDEsInN1YiI6IjZjNDFjNTgzLTk4YzItNGRkZS1iMjNhLTcyNjFhNmQ3ZGUwMiJ9.XCRyzPi9iJffHYr1Cb3mBlh_Aom4yEHL2UodRBVqANs